---
keycloak:
  extraEnvVars:
    - name: KEYCLOAK_LOG_LEVEL
      value: DEBUG


ingress:
  enabled: true
  hostname: cloud.keycloak.stfc.ac.uk
  ingressClassName: nginx
  path: /
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
  selfSigned: true
  tls: true

metrics:
  enabled: true
  service:
    ports:
      http: 8080
      https: 8443
      metrics: 9000
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/realms/master/metrics"
      prometheus.io/port: "9000"

service:
  type: NodePort
  nodePorts:
    http: 30080

postgresql:
  enabled: true
  postgresqlDatabase: keycloakdb
  postgresqlUsername: <USERNAME>
  postgresqlPassword: <PASSWORD>

readinessProbe:
  httpGet:
    path: /realms/master
    port: http
  initialDelaySeconds: 60
  timeoutSeconds: 5

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
