---
alertmanager:
  enabled: true
  service:
    # Input desired LB floating IP in quotation marks, floating IP needs to be assigned to project
    loadBalancerIP: <LB IP>


server:
  service:
    # Input desired LB floating IP in quotation marks, floating IP needs to be assigned to project
    loadBalancerIP: <LB IP>
  scrapeInterval: 2m
  # Generic manual scrape configs to pick up metrics from Keycloak metrics source.
  extraScrapeConfigs:
    - job_name: keycloak
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - keycloak
      metrics_path: /metrics
      basic_auth:
        # Input username and password for basic authentication if required, elsewise remove.
        username: <USERNAME>
        password: <PASSWORD>
      relabel_configs:
        - source_labels:
            - job
          target_label: __tmp_keycloak_job_name
        - action: keep
          source_labels:
            - __meta_kubernetes_service_label_app_kubernetes_io_instance
            - __meta_kubernetes_service_labelpresent_app_kubernetes_io_instance
          regex: (keycloak);true
        - action: keep
          source_labels:
            - __meta_kubernetes_service_label_app_kubernetes_io_name
            - __meta_kubernetes_service_labelpresent_app_kubernetes_io_name
          regex: (keycloak);true
        - action: keep
          source_labels:
            - __meta_kubernetes_endpoint_port_name
          regex: metrics
        - source_labels:
            - __meta_kubernetes_endpoint_address_target_kind
            - __meta_kubernetes_endpoint_address_target_name
          separator: ;
          regex: Node;(.*)
          replacement: ${1}
          target_label: node
        - source_labels:
            - __meta_kubernetes_endpoint_address_target_kind
            - __meta_kubernetes_endpoint_address_target_name
          separator: ;
          regex: Pod;(.*)
          replacement: ${1}
          target_label: pod
        - source_labels:
            - __meta_kubernetes_namespace
          target_label: namespace
        - source_labels:
            - __meta_kubernetes_service_name
          target_label: service
        - source_labels:
            - __meta_kubernetes_pod_name
          target_label: pod
        - source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: container
        - action: drop
          source_labels:
            - __meta_kubernetes_pod_phase
          regex: (Failed|Succeeded)
        - source_labels:
            - __meta_kubernetes_service_name
          target_label: job
          replacement: ${1}
        - target_label: endpoint
          replacement: metrics
        - source_labels:
            - __address__
          target_label: __tmp_hash
          modulus: 1
          action: hashmod
        - source_labels:
            - __tmp_hash
          regex: 0
          action: keep
