apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: [EMAIL HERE]
    privateKeySecretRef:
      name: [PRIVKEY REF STRING HERE]
    solvers:
    - http01:
        ingress:
          class: nginx

