---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: [EMAIL HERE]
    # Include email the certificate should be registered to.
    privateKeySecretRef:
      # Include a random string as a secret ref, by default should be: "letsencrypt-prod"
      name: [PRIVKEY REF STRING HERE]
    solvers:
    - http01:
        ingress:
          class: nginx
